  
 -- Inserción de datos en la tabla Genre
INSERT INTO Genre (idGenre, nameTheme) VALUES ("2", "Point-and-click");
INSERT INTO Genre (idGenre, nameTheme) VALUES ("4", "Fighting");
INSERT INTO Genre (idGenre, nameTheme) VALUES ("5", "Shooter");
INSERT INTO Genre (idGenre, nameTheme) VALUES ("7", "Music");
INSERT INTO Genre (idGenre, nameTheme) VALUES ("8", "Platform");
INSERT INTO Genre (idGenre, nameTheme) VALUES ("9", "Puzzle");
INSERT INTO Genre (idGenre, nameTheme) VALUES ("10", "Racing");
INSERT INTO Genre (idGenre, nameTheme) VALUES ("11", "Real Time Strategy (RTS)");
INSERT INTO Genre (idGenre, nameTheme) VALUES ("12", "Role-playing (RPG)");
INSERT INTO Genre (idGenre, nameTheme) VALUES ("13", "Simulator");
INSERT INTO Genre (idGenre, nameTheme) VALUES ("14", "Sport");
INSERT INTO Genre (idGenre, nameTheme) VALUES ("15", "Strategy");
INSERT INTO Genre (idGenre, nameTheme) VALUES ("16", "Turn-based strategy (TBS)");
INSERT INTO Genre (idGenre, nameTheme) VALUES ("24", "Tactical");
INSERT INTO Genre (idGenre, nameTheme) VALUES ("25", "Hack and slash/Beat 'em up");
INSERT INTO Genre (idGenre, nameTheme) VALUES ("26", "Quiz/Trivia");
INSERT INTO Genre (idGenre, nameTheme) VALUES ("30", "Pinball");
INSERT INTO Genre (idGenre, nameTheme) VALUES ("31", "Adventure");
INSERT INTO Genre (idGenre, nameTheme) VALUES ("32", "Indie");
INSERT INTO Genre (idGenre, nameTheme) VALUES ("33", "Arcade");
INSERT INTO Genre (idGenre, nameTheme) VALUES ("34", "Visual Novel");
INSERT INTO Genre (idGenre, nameTheme) VALUES ("35", "Card & Board Game");
INSERT INTO Genre (idGenre, nameTheme) VALUES ("36", "MOBA");

 -- Inserción de datos en la tabla Platform
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("3", "Linux");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("4", "Nintendo 64");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("5", "Wii");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("6", "PC (Microsoft Windows)");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("7", "PlayStation");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("8", "PlayStation 2");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("9", "PlayStation 3");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("11", "Xbox");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("12", "Xbox 360");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("13", "DOS");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("14", "Mac");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("15", "Commodore C64/128/MAX");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("16", "Amiga");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("18", "Nintendo Entertainment System");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("19", "Super Nintendo Entertainment System");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("20", "Nintendo DS");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("21", "Nintendo GameCube");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("22", "Game Boy Color");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("23", "Dreamcast");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("24", "Game Boy Advance");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("25", "Amstrad CPC");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("26", "ZX Spectrum");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("27", "MSX");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("29", "Sega Mega Drive/Genesis");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("30", "Sega 32X");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("32", "Sega Saturn");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("33", "Game Boy");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("34", "Android");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("35", "Sega Game Gear");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("37", "Nintendo 3DS");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("38", "PlayStation Portable");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("39", "iOS");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("41", "Wii U");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("42", "N-Gage");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("44", "Tapwave Zodiac");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("46", "PlayStation Vita");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("47", "Virtual Console");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("48", "PlayStation 4");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("49", "Xbox One");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("50", "3DO Interactive Multiplayer");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("51", "Family Computer Disk System");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("52", "Arcade");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("53", "MSX2");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("55", "Legacy Mobile Device");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("57", "WonderSwan");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("58", "Super Famicom");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("59", "Atari 2600");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("60", "Atari 7800");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("61", "Atari Lynx");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("62", "Atari Jaguar");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("63", "Atari ST/STE");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("64", "Sega Master System/Mark III");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("65", "Atari 8-bit");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("66", "Atari 5200");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("67", "Intellivision");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("68", "ColecoVision");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("69", "BBC Microcomputer System");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("70", "Vectrex");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("71", "Commodore VIC-20");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("72", "Ouya");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("73", "BlackBerry OS");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("74", "Windows Phone");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("75", "Apple II");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("77", "Sharp X1");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("78", "Sega CD");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("79", "Neo Geo MVS");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("80", "Neo Geo AES");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("82", "Web browser");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("84", "SG-1000");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("85", "Donner Model 30");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("86", "TurboGrafx-16/PC Engine");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("87", "Virtual Boy");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("88", "Odyssey");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("89", "Microvision");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("90", "Commodore PET");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("91", "Bally Astrocade");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("93", "Commodore 16");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("94", "Commodore Plus/4");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("95", "PDP-1");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("96", "PDP-10");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("97", "PDP-8");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("98", "DEC GT40");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("99", "Family Computer");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("100", "Analogue electronics");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("101", "Ferranti Nimrod Computer");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("102", "EDSAC");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("103", "PDP-7");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("104", "HP 2100");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("105", "HP 3000");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("106", "SDS Sigma 7");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("107", "Call-A-Computer time-shared mainframe computer system");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("108", "PDP-11");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("109", "CDC Cyber 70");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("110", "PLATO");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("111", "Imlac PDS-1");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("112", "Microcomputer");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("113", "OnLive Game System");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("114", "Amiga CD32");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("115", "Apple IIGS");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("116", "Acorn Archimedes");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("117", "Philips CD-i");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("118", "FM Towns");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("119", "Neo Geo Pocket");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("120", "Neo Geo Pocket Color");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("121", "Sharp X68000");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("122", "Nuon");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("123", "WonderSwan Color");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("124", "SwanCrystal");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("125", "PC-8800 Series");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("126", "TRS-80");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("127", "Fairchild Channel F");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("128", "PC Engine SuperGrafx");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("129", "Texas Instruments TI-99");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("130", "Nintendo Switch");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("131", "Nintendo PlayStation");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("132", "Amazon Fire TV");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("133", "Odyssey 2 / Videopac G7000");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("134", "Acorn Electron");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("135", "Hyper Neo Geo 64");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("136", "Neo Geo CD");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("137", "New Nintendo 3DS");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("138", "VC 4000");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("139", "1292 Advanced Programmable Video System");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("140", "AY-3-8500");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("141", "AY-3-8610");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("142", "PC-50X Family");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("143", "AY-3-8760");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("144", "AY-3-8710");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("145", "AY-3-8603");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("146", "AY-3-8605");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("147", "AY-3-8606");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("148", "AY-3-8607");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("149", "PC-9800 Series");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("150", "Turbografx-16/PC Engine CD");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("151", "TRS-80 Color Computer");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("152", "FM-7");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("153", "Dragon 32/64");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("154", "Amstrad PCW");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("155", "Tatung Einstein");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("156", "Thomson MO5");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("157", "NEC PC-6000 Series");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("158", "Commodore CDTV");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("159", "Nintendo DSi");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("161", "Windows Mixed Reality");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("162", "Oculus VR");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("163", "SteamVR");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("164", "Daydream");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("165", "PlayStation VR");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("166", "Pokémon mini");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("167", "PlayStation 5");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("169", "Xbox Series X|S");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("170", "Google Stadia");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("203", "DUPLICATE Stadia");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("236", "Exidy Sorcerer");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("237", "Sol-20");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("238", "DVD Player");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("239", "Blu-ray Player");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("240", "Zeebo");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("274", "PC-FX");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("306", "Satellaview");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("307", "Game & Watch");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("308", "Playdia");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("309", "Evercade");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("339", "Sega Pico");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("372", "OOParts");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("373", "Sinclair ZX81");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("374", "Sharp MZ-2200");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("375", "Epoch Cassette Vision");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("376", "Epoch Super Cassette Vision");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("377", "Plug & Play");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("378", "Gamate");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("379", "Game.com");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("380", "Casio Loopy");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("381", "Playdate");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("382", "Intellivision Amico");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("384", "Oculus Quest");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("385", "Oculus Rift");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("386", "Meta Quest 2");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("387", "Oculus Go");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("388", "Gear VR");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("389", "AirConsole");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("390", "PlayStation VR2");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("405", "Windows Mobile");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("406", "Sinclair QL");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("407", "HyperScan");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("408", "Mega Duck/Cougar Boy");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("409", "Legacy Computer");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("410", "Atari Jaguar CD");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("411", "Handheld Electronic LCD");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("412", "Leapster");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("413", "Leapster Explorer/LeadPad Explorer");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("414", "LeapTV");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("415", "Watara/QuickShot Supervision");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("416", "Nintendo 64DD");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("417", "Palm OS");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("438", "Arduboy");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("439", "V.Smile");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("440", "Visual Memory Unit / Visual Memory System");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("441", "PocketStation");
INSERT INTO Platform (idPlatform, namePlatform) VALUES ("471", "Meta Quest 3");
