SELECT * FROM HABITACION;
SELECT COUNT(*) FROM HABITACION;

SELECT * FROM PACIENTE LIMIT 10;
SELECT COUNT(*) FROM PACIENTE;

SELECT * FROM LOG_ACTIVIDAD ORDER BY id_log_actividad DESC LIMIT 10;
SELECT COUNT(*) FROM LOG_ACTIVIDAD;

SELECT * FROM LOG_HABITACION ORDER BY timestampx DESC LIMIT 10;
SELECT COUNT(*) FROM LOG_HABITACION;



DELETE FROM HABITACION;
DELETE FROM PACIENTE;
DELETE FROM LOG_ACTIVIDAD;
DELETE FROM LOG_HABITACION;

SELECT COUNT(*) FROM HABITACION;
SELECT COUNT(*) FROM PACIENTE;
SELECT COUNT(*) FROM LOG_ACTIVIDAD;
SELECT COUNT(*) FROM LOG_HABITACION;
