-- MySQL Script generated by MySQL Workbench
-- vie 22 sep 2023 22:59:57
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`AgeRating`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`AgeRating` ;

CREATE TABLE IF NOT EXISTS `mydb`.`AgeRating` (
  `idAgeRating` INT NOT NULL,
  `synopsis` VARCHAR(300) NOT NULL,
  `idRatingCategory` INT NOT NULL,
  PRIMARY KEY (`idAgeRating`, `idRatingCategory`),
  INDEX `fk_AgeRating_AgeRatingCategory1_idx` (`idRatingCategory` ASC) VISIBLE,
  CONSTRAINT `fk_AgeRating_AgeRatingCategory1`
    FOREIGN KEY (`idRatingCategory`)
    REFERENCES `mydb`.`RatingCategory` (`idRatingCategory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`AlternativeName`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`AlternativeName` ;

CREATE TABLE IF NOT EXISTS `mydb`.`AlternativeName` (
  `idAlternativeName` INT NOT NULL,
  `comment` VARCHAR(100) NULL,
  `idGame` INT NOT NULL,
  `alternativeName` VARCHAR(45) NULL,
  PRIMARY KEY (`idAlternativeName`, `idGame`),
  INDEX `fk_AlternativeName_Game1_idx` (`idGame` ASC) VISIBLE,
  CONSTRAINT `fk_AlternativeName_Game1`
    FOREIGN KEY (`idGame`)
    REFERENCES `mydb`.`Game` (`idGame`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Category` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Category` (
  `idCategory` INT NOT NULL,
  `nameCategory` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`idCategory`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Company`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Company` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Company` (
  `idCompany` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NOT NULL,
  `description` VARCHAR(800) NOT NULL,
  `ratingProm` DECIMAL(5,2) NOT NULL,
  `ratingCount` INT NOT NULL,
  `country` VARCHAR(80) NOT NULL,
  `established` DATE NULL,
  `status` VARCHAR(45) NULL,
  `website` VARCHAR(200) NULL,
  `socialMediaLinks` VARCHAR(45) NULL,
  PRIMARY KEY (`idCompany`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Game`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Game` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Game` (
  `idGame` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `summary` VARCHAR(5000) NULL,
  `storyline` VARCHAR(5000) NULL,
  `rating` DECIMAL(6,2) NULL,
  `ratingCount` INT NULL,
  `aggregatedRating` DECIMAL(6,2) NULL,
  `aggregatedRatingCount` INT NULL,
  `totalRating` DOUBLE(6,2) NULL,
  `totalRatingCount` INT NULL,
  `firstReleaseDate` DATE NULL,
  `keywords` VARCHAR(1000) NULL,
  `screenshots` VARCHAR(1000) NULL,
  `videos` VARCHAR(1000) NULL,
  `coverImage` VARCHAR(20) NULL,
  `artworks` VARCHAR(45) NULL,
  `websites` VARCHAR(1000) NULL,
  `parentGame` INT NULL,
  `idStatus` INT NOT NULL,
  `idCategory` INT NOT NULL,
  PRIMARY KEY (`idGame`),
  INDEX `fk_Game_Game_idx` (`parentGame` ASC) VISIBLE,
  INDEX `fk_Game_GameStatus1_idx` (`idStatus` ASC) VISIBLE,
  INDEX `fk_Game_Category1_idx` (`idCategory` ASC) VISIBLE,
  CONSTRAINT `fk_Game_Game`
    FOREIGN KEY (`parentGame`)
    REFERENCES `mydb`.`Game` (`idGame`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Game_GameStatus1`
    FOREIGN KEY (`idStatus`)
    REFERENCES `mydb`.`GameStatus` (`idGameStatus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Game_Category1`
    FOREIGN KEY (`idCategory`)
    REFERENCES `mydb`.`Category` (`idCategory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`GameAgeRating`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`GameAgeRating` ;

CREATE TABLE IF NOT EXISTS `mydb`.`GameAgeRating` (
  `idAgeRating` INT NOT NULL,
  `idRatingCategory` INT NOT NULL,
  `dGame` INT NOT NULL,
  PRIMARY KEY (`idAgeRating`, `idRatingCategory`, `dGame`),
  INDEX `fk_AgeRating_has_Game_Game1_idx` (`dGame` ASC) VISIBLE,
  INDEX `fk_AgeRating_has_Game_AgeRating1_idx` (`idAgeRating` ASC, `idRatingCategory` ASC) VISIBLE,
  CONSTRAINT `fk_AgeRating_has_Game_AgeRating1`
    FOREIGN KEY (`idAgeRating` , `idRatingCategory`)
    REFERENCES `mydb`.`AgeRating` (`idAgeRating` , `idRatingCategory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AgeRating_has_Game_Game1`
    FOREIGN KEY (`dGame`)
    REFERENCES `mydb`.`Game` (`idGame`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`GameGenre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`GameGenre` ;

CREATE TABLE IF NOT EXISTS `mydb`.`GameGenre` (
  `idGenre` INT NOT NULL,
  `idGame` INT NOT NULL,
  PRIMARY KEY (`idGenre`, `idGame`),
  INDEX `fk_Genre_has_Game_Game1_idx` (`idGame` ASC) VISIBLE,
  INDEX `fk_Genre_has_Game_Genre1_idx` (`idGenre` ASC) VISIBLE,
  CONSTRAINT `fk_Genre_has_Game_Genre1`
    FOREIGN KEY (`idGenre`)
    REFERENCES `mydb`.`Genre` (`idGenre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Genre_has_Game_Game1`
    FOREIGN KEY (`idGame`)
    REFERENCES `mydb`.`Game` (`idGame`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`GameLocalization`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`GameLocalization` ;

CREATE TABLE IF NOT EXISTS `mydb`.`GameLocalization` (
  `idGame` INT NOT NULL,
  `idRegion` INT NOT NULL,
  `name` VARCHAR(100) NULL,
  `uploatedAt` DATE NULL,
  PRIMARY KEY (`idGame`, `idRegion`),
  INDEX `fk_Game_has_Region_Region1_idx` (`idRegion` ASC) VISIBLE,
  INDEX `fk_Game_has_Region_Game1_idx` (`idGame` ASC) VISIBLE,
  CONSTRAINT `fk_Game_has_Region_Game1`
    FOREIGN KEY (`idGame`)
    REFERENCES `mydb`.`Game` (`idGame`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Game_has_Region_Region1`
    FOREIGN KEY (`idRegion`)
    REFERENCES `mydb`.`Region` (`idRegion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`GameMode`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`GameMode` ;

CREATE TABLE IF NOT EXISTS `mydb`.`GameMode` (
  `idMode` INT NOT NULL,
  `idGame` INT NOT NULL,
  PRIMARY KEY (`idMode`, `idGame`),
  INDEX `fk_Mode_has_Game_Game1_idx` (`idGame` ASC) VISIBLE,
  INDEX `fk_Mode_has_Game_Mode1_idx` (`idMode` ASC) VISIBLE,
  CONSTRAINT `fk_Mode_has_Game_Mode1`
    FOREIGN KEY (`idMode`)
    REFERENCES `mydb`.`Mode` (`idMode`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Mode_has_Game_Game1`
    FOREIGN KEY (`idGame`)
    REFERENCES `mydb`.`Game` (`idGame`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`GamePerspective`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`GamePerspective` ;

CREATE TABLE IF NOT EXISTS `mydb`.`GamePerspective` (
  `idPlayerPerspective` INT NOT NULL,
  `idGame` INT NOT NULL,
  PRIMARY KEY (`idPlayerPerspective`, `idGame`),
  INDEX `fk_PlayerPerspective_has_Game_Game1_idx` (`idGame` ASC) VISIBLE,
  INDEX `fk_PlayerPerspective_has_Game_PlayerPerspective1_idx` (`idPlayerPerspective` ASC) VISIBLE,
  CONSTRAINT `fk_PlayerPerspective_has_Game_PlayerPerspective1`
    FOREIGN KEY (`idPlayerPerspective`)
    REFERENCES `mydb`.`PlayerPerspective` (`idPlayerPerspective`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PlayerPerspective_has_Game_Game1`
    FOREIGN KEY (`idGame`)
    REFERENCES `mydb`.`Game` (`idGame`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`GameStatus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`GameStatus` ;

CREATE TABLE IF NOT EXISTS `mydb`.`GameStatus` (
  `idGameStatus` INT NOT NULL,
  `nameStatus` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`idGameStatus`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`GameTheme`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`GameTheme` ;

CREATE TABLE IF NOT EXISTS `mydb`.`GameTheme` (
  `idTheme` INT NOT NULL,
  `idGame` INT NOT NULL,
  PRIMARY KEY (`idTheme`, `idGame`),
  INDEX `fk_Theme_has_Game_Game1_idx` (`idGame` ASC) VISIBLE,
  INDEX `fk_Theme_has_Game_Theme1_idx` (`idTheme` ASC) VISIBLE,
  CONSTRAINT `fk_Theme_has_Game_Theme1`
    FOREIGN KEY (`idTheme`)
    REFERENCES `mydb`.`Theme` (`idTheme`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Theme_has_Game_Game1`
    FOREIGN KEY (`idGame`)
    REFERENCES `mydb`.`Game` (`idGame`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Genre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Genre` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Genre` (
  `idGenre` INT NOT NULL,
  `nameTheme` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idGenre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`InvolvedCompanies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`InvolvedCompanies` ;

CREATE TABLE IF NOT EXISTS `mydb`.`InvolvedCompanies` (
  `idCompany` INT NOT NULL,
  `idGame` INT NOT NULL,
  `developer` TINYINT NULL,
  `porting` TINYINT NULL,
  `publisher` TINYINT NULL,
  `supporting` TINYINT NULL,
  PRIMARY KEY (`idCompany`, `idGame`),
  INDEX `fk_Company_has_Game_Game1_idx` (`idGame` ASC) VISIBLE,
  INDEX `fk_Company_has_Game_Company1_idx` (`idCompany` ASC) VISIBLE,
  CONSTRAINT `fk_Company_has_Game_Company1`
    FOREIGN KEY (`idCompany`)
    REFERENCES `mydb`.`Company` (`idCompany`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Company_has_Game_Game1`
    FOREIGN KEY (`idGame`)
    REFERENCES `mydb`.`Game` (`idGame`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Language`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Language` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Language` (
  `idLanguage` INT NOT NULL,
  `nameLanguage` VARCHAR(100) NOT NULL,
  `nativeName` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idLanguage`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`LanguageGame`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`LanguageGame` ;

CREATE TABLE IF NOT EXISTS `mydb`.`LanguageGame` (
  `idGame` INT NOT NULL,
  `idLanguage` INT NOT NULL,
  `audio` VARCHAR(45) NULL,
  `subtitles` VARCHAR(100) NULL,
  `interface` VARCHAR(100) NULL,
  PRIMARY KEY (`idGame`, `idLanguage`),
  INDEX `fk_Game_has_Language_Language1_idx` (`idLanguage` ASC) VISIBLE,
  INDEX `fk_Game_has_Language_Game1_idx` (`idGame` ASC) VISIBLE,
  CONSTRAINT `fk_Game_has_Language_Game1`
    FOREIGN KEY (`idGame`)
    REFERENCES `mydb`.`Game` (`idGame`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Game_has_Language_Language1`
    FOREIGN KEY (`idLanguage`)
    REFERENCES `mydb`.`Language` (`idLanguage`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Mode`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Mode` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Mode` (
  `idMode` INT NOT NULL,
  `nameMode` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idMode`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Platform`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Platform` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Platform` (
  `idPlatform` INT NOT NULL,
  `namePlatform` VARCHAR(100) NOT NULL,
  `manufacturer` VARCHAR(200) NOT NULL,
  `releaseDate` DATE NOT NULL,
  `onlineFeatures` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPlatform`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PlatformGame`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`PlatformGame` ;

CREATE TABLE IF NOT EXISTS `mydb`.`PlatformGame` (
  `idGame` INT NOT NULL,
  `idPlatform` INT NOT NULL,
  `dateRelease` DATE NOT NULL,
  `price` DECIMAL(7,2) NOT NULL,
  `availability` VARCHAR(100) NULL,
  PRIMARY KEY (`idGame`, `idPlatform`),
  INDEX `fk_Game_has_Platform_Platform1_idx` (`idPlatform` ASC) VISIBLE,
  INDEX `fk_Game_has_Platform_Game1_idx` (`idGame` ASC) VISIBLE,
  CONSTRAINT `fk_Game_has_Platform_Game1`
    FOREIGN KEY (`idGame`)
    REFERENCES `mydb`.`Game` (`idGame`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Game_has_Platform_Platform1`
    FOREIGN KEY (`idPlatform`)
    REFERENCES `mydb`.`Platform` (`idPlatform`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PlayerPerspective`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`PlayerPerspective` ;

CREATE TABLE IF NOT EXISTS `mydb`.`PlayerPerspective` (
  `idPlayerPerspective` INT NOT NULL,
  `namePlayerPersective` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idPlayerPerspective`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`RatingCategory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`RatingCategory` ;

CREATE TABLE IF NOT EXISTS `mydb`.`RatingCategory` (
  `idRatingCategory` INT NOT NULL,
  `nameTheme` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idRatingCategory`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Region`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Region` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Region` (
  `idRegion` INT NOT NULL,
  `nameRegion` VARCHAR(100) NOT NULL,
  `continent` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idRegion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Theme`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Theme` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Theme` (
  `idTheme` INT NOT NULL,
  `nameTheme` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idTheme`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
